name: linting, testing, building
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn
      - name: build prod project
        if: always()
        run: yarn build:prod
      - name: lint ts
        if: always()
        run: yarn lint:ts
      - name: lint scss
        if: always()
        run: yarn lint:scss
      - name: unit tests
        if: always()
        run: yarn test:unit
      - name: build storybook
        if: always()
        run: yarn storybook:build
      - name: test ui
        if: always()
        run: yarn test:ui:ci
